version: '2'

services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/myapp
        depends_on:
            - redis
    redis:
        image: redis
